//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

#pragma warning disable 1591

namespace ERP.Web.bd.com.mobireach.user {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="SmsControllerBinding", Namespace="urn:SmsControllerwsdl")]
    public partial class SmsControllerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMessageStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTextMultiMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTextMessageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SmsControllerService() {
            this.Url = global::ERP.Web.Properties.Settings.Default.UcasPortfolio_Web_bd_com_mobireach_user_SmsControllerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMessageStatusCompletedEventHandler GetMessageStatusCompleted;
        
        /// <remarks/>
        public event SendTextMultiMessageCompletedEventHandler SendTextMultiMessageCompleted;
        
        /// <remarks/>
        public event SendTextMessageCompletedEventHandler SendTextMessageCompleted;
        
        /// <remarks/>
        [SoapRpcMethod("urn:SmsControllerwsdl#GetMessageStatus", RequestNamespace="urn:SmsControllerwsdl", ResponseNamespace="urn:SmsControllerwsdl")]
        [return: SoapElement("return")]
        public ServiceClass GetMessageStatus(string Username, string Password, string MessageId) {
            object[] results = this.Invoke("GetMessageStatus", new object[] {
                        Username,
                        Password,
                        MessageId});
            return ((ServiceClass)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageStatusAsync(string Username, string Password, string MessageId) {
            this.GetMessageStatusAsync(Username, Password, MessageId, null);
        }
        
        /// <remarks/>
        public void GetMessageStatusAsync(string Username, string Password, string MessageId, object userState) {
            if ((this.GetMessageStatusOperationCompleted == null)) {
                this.GetMessageStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageStatusOperationCompleted);
            }
            this.InvokeAsync("GetMessageStatus", new object[] {
                        Username,
                        Password,
                        MessageId}, this.GetMessageStatusOperationCompleted, userState);
        }
        
        private void OnGetMessageStatusOperationCompleted(object arg) {
            if ((this.GetMessageStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageStatusCompleted(this, new GetMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapRpcMethod("urn:SmsControllerwsdl#SendTextMultiMessage", RequestNamespace="urn:SmsControllerwsdl", ResponseNamespace="urn:SmsControllerwsdl")]
        [return: SoapElement("return")]
        public ServiceClassArray SendTextMultiMessage(string Username, string Password, string From, string To, string Message) {
            object[] results = this.Invoke("SendTextMultiMessage", new object[] {
                        Username,
                        Password,
                        From,
                        To,
                        Message});
            return ((ServiceClassArray)(results[0]));
        }
        
        /// <remarks/>
        public void SendTextMultiMessageAsync(string Username, string Password, string From, string To, string Message) {
            this.SendTextMultiMessageAsync(Username, Password, From, To, Message, null);
        }
        
        /// <remarks/>
        public void SendTextMultiMessageAsync(string Username, string Password, string From, string To, string Message, object userState) {
            if ((this.SendTextMultiMessageOperationCompleted == null)) {
                this.SendTextMultiMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTextMultiMessageOperationCompleted);
            }
            this.InvokeAsync("SendTextMultiMessage", new object[] {
                        Username,
                        Password,
                        From,
                        To,
                        Message}, this.SendTextMultiMessageOperationCompleted, userState);
        }
        
        private void OnSendTextMultiMessageOperationCompleted(object arg) {
            if ((this.SendTextMultiMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTextMultiMessageCompleted(this, new SendTextMultiMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapRpcMethod("urn:SmsControllerwsdl#SendTextMessage", RequestNamespace="urn:SmsControllerwsdl", ResponseNamespace="urn:SmsControllerwsdl")]
        [return: SoapElement("return")]
        public ServiceClass SendTextMessage(string Username, string Password, string From, string To, string Message) {
            object[] results = this.Invoke("SendTextMessage", new object[] {
                        Username,
                        Password,
                        From,
                        To,
                        Message});
            return ((ServiceClass)(results[0]));
        }
        
        /// <remarks/>
        public void SendTextMessageAsync(string Username, string Password, string From, string To, string Message) {
            this.SendTextMessageAsync(Username, Password, From, To, Message, null);
        }
        
        /// <remarks/>
        public void SendTextMessageAsync(string Username, string Password, string From, string To, string Message, object userState) {
            if ((this.SendTextMessageOperationCompleted == null)) {
                this.SendTextMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTextMessageOperationCompleted);
            }
            this.InvokeAsync("SendTextMessage", new object[] {
                        Username,
                        Password,
                        From,
                        To,
                        Message}, this.SendTextMessageOperationCompleted, userState);
        }
        
        private void OnSendTextMessageOperationCompleted(object arg) {
            if ((this.SendTextMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTextMessageCompleted(this, new SendTextMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="urn:SmsControllerwsdl")]
    public partial class ServiceClass {
        
        private string messageIDField;
        
        private string statusField;
        
        private string statusTextField;
        
        private string errorCodeField;
        
        private string errorTextField;
        
        private string sMSCountField;
        
        private float currentCreditField;
        
        /// <remarks/>
        [SoapElement(DataType="integer")]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(DataType="integer")]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(DataType="integer")]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(DataType="integer")]
        public string SMSCount {
            get {
                return this.sMSCountField;
            }
            set {
                this.sMSCountField = value;
            }
        }
        
        /// <remarks/>
        public float CurrentCredit {
            get {
                return this.currentCreditField;
            }
            set {
                this.currentCreditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="urn:SmsControllerwsdl")]
    public partial class ServiceClassArray {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetMessageStatusCompletedEventHandler(object sender, GetMessageStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GetMessageStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SendTextMultiMessageCompletedEventHandler(object sender, SendTextMultiMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class SendTextMultiMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTextMultiMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceClassArray Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceClassArray)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SendTextMessageCompletedEventHandler(object sender, SendTextMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class SendTextMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTextMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceClass)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591